development:
  api:
    google: ABQIAAAA9rWAXwsosqg0R8Lfc9vBnhTJQa0g3IQ9GZqIMmInSLzwtGDKaBTQ7nIj8VvdVz64uIk2xb3LT1egWg # localhost:3000
    facebook:
      AppId: '202254456452409'

production:
  api:
    google: ABQIAAAA9rWAXwsosqg0R8Lfc9vBnhSZIZ6q54I5-XTOKEUHtew-Vkt3PRQ_9SMpkzyCv8nY_yPQZOtGBaM6NA # werstreikt.de
    facebook:
      AppId: '114907251917062'
